### ISSUE TITLE
Namespace in external DLL causes issues in component code generation.

### ISSUE THREAD

**Issue by nfoste82** [sschmid/Entitas-CSharp#795] opened 2018-09-19 19:37 UTC
I have an enum in a namespace in a DLL that is separate from the code that has my components in it. I'm using that enum in a component. 
- If I use a 'using' directive at the top of the component then the generated code doesn't bring that over or fully qualify the namespace for the type. 
- If the enum is in the same DLL as the components then the generated code does fully quality the namespace and will compile. 
- If the enum is left in a separate DLL but I fully qualify the namespace in the component, then the generated code will fully qualify the namespace and compile.

Here's some code

```csharp
// This is in Foo.dll
namespace Foo
{
    public enum Color
    {
        Blue,
        Red,
        Yellow,
        Green,
        Purple,
    }
}
```

```csharp
// This is in Bar.dll
using Foo;
using Entitas;

namespace Bar.Components
{
    [Game]
    public class ColorComponent : IComponent
    {
        public Color color;
    }
}
```

```csharp
// Generated code, in Bar.dll
public partial class GameEntity {

public Bar.Components.ColorComponent color { get { return (Bar.Components.ColorComponent)GetComponent(GameComponentsLookup.Color); } }
public bool hasColor { get { return HasComponent(GameComponentsLookup.Color); } }

// *** The new line is what fails to compile. The function parameter, Color, is not found ***
public void AddColor(Color newColor) {
    var index = GameComponentsLookup.Color;
    var component = CreateComponent<Bar.Components.ColorComponent>(index);
    component.color = newColor;
    AddComponent(index, component);
}

...
```

If I fully quality the type in my component instead of using a `using`, then the code generator seems to pick that up.
```csharp
// This is in Bar.dll
using Entitas;

namespace Bar.Components
{
    [Game]
    public class ColorComponent : IComponent
    {
        public Foo.Color color;
    }
}
```

```csharp
// Generated code, in Bar.dll
public partial class GameEntity {

public Bar.Components.ColorComponent color { get { return (Bar.Components.ColorComponent)GetComponent(GameComponentsLookup.Color); } }
public bool hasColor { get { return HasComponent(GameComponentsLookup.Color); } }

// *** Fully qualified type is now listed here ***
public void AddColor(Foo.Color newColor) {
    var index = GameComponentsLookup.Color;
    var component = CreateComponent<Bar.Components.ColorComponent>(index);
    component.color = newColor;
    AddComponent(index, component);
}

...
```

**Comment by nfoste82** [comment] 2018-09-19 22:35
I added both the path to the folder with the source itself and the path to the folder with the .dll, to the Jenny.SearchPaths, and that didn't seem to have any effect.

**Comment by sschmid** [comment] 2018-09-20 01:46
Cannot reproduce, works for me.
With which .NET version is the dll compiled?

**Comment by nfoste82** [comment] 2018-09-20 15:20
.NET 4.7.1 for both dlls.

I'm able to work around the issue for now by using the full namespace in the component variables. So this isn't a blocking issue. Just seemed like it might be a bug. It's a shame you can't reproduce it though.

**Comment by sschmid** [comment] 2018-10-05 18:36
I hope your fine with the workaround. Sorry that I couldn't reproduce. When in doubt, you can send me stripped down demo project with you specific setup so I can try. Will close the issue for now

**Closed by sschmid** 2018-10-05 18:36 UTC
