### ISSUE TITLE
Inconsistent Line endings

### ISSUE THREAD

**Issue by ParagonFable** [sschmid/Entitas-CSharp#116] opened 2016-06-03 01:15 UTC
The current code generator is using the following to transform generated code to Unix Line Endings:

`str.Replace(Environment.NewLine, "\n");`

However, on Win systems that have been configured to use Unix style line endings there still seems to be a handful of CRLF codes in the generated files and the above method does not catch them. A better solution would be to simply match against the actual unwanted characters:

`str.Replace("\r\n", "\n").Replace("\r", "\n");`

This removes any dependency on having the correct system configuration to function as intended. Note: Order or operations matters with the above code.

**Comment by sschmid** [comment] 2016-06-14 22:14
Wow, never heard
> Win systems that have been configured to use Unix style line endings

:)
Thanks for letting me know, I'll update!

**Comment by jakovd** [comment] 2016-08-02 06:25
I was still getting inconsistent line endings for Generated/ComponentIds.cs on Windows machine. The fix works fine. Since it has been proposed 2 months ago it should have already made into the source by now. Don't you think?

**Comment by sschmid** [comment] 2016-08-27 01:52
Thanks! Sorry, took a while. Will be in the next release

**Closed by sschmid** 2016-08-27 01:52 UTC
Labels: enhancement, ready

**Comment by AllanSamurai** [comment] 2016-12-15 21:00
In windows 10 64 i still had this problem but only the header it was causing.
I resolved thus on file CodeGenerator.cs method "writeFiles" change this:
`                var header = string.Format(AUTO_GENERATED_HEADER_FORMAT, file.generatorName);`
to this:
`	            var header = string.Format(AUTO_GENERATED_HEADER_FORMAT.Replace("\n",Environment.NewLine), file.generatorName);`
Sorry my bad english.

**Comment by sschmid** [comment] 2016-12-15 21:39
@AllanSamurai Thanks!
I don't have a windows 10 machine right now, but you could help me verify if this fixes it:
Can you replace CodeGenerator.writeFiles() method with this code and see if it the issue is fixed?

`CodeGenerator.cs`
```csharp
        static void writeFiles(string directory, CodeGenFile[] files) {
            if(!Directory.Exists(directory)) {
                Directory.CreateDirectory(directory);
            }
            foreach(var file in files) {
                var fileName = directory + file.fileName + ".cs";
                var header = string.Format(AUTO_GENERATED_HEADER_FORMAT, file.generatorName);
                var fileContent = (header + file.fileContent).Replace("\n", Environment.NewLine);
                File.WriteAllText(fileName, fileContent);
            }
        }
```

**Comment by AllanSamurai** [comment] 2016-12-15 21:48
Tested on my own project and on Entitas-Shmup project too
it fixes
:D
Thank you!

**Comment by sschmid** [comment] 2016-12-15 21:51
Awesome, will be in the next release
bb83d990c59266d6605da94a95389195a892a4ec
