### ISSUE TITLE
Relace a  Component  more then once At one frame  Only get the Last Reactive   

### ISSUE THREAD

**Issue by xiaomingfun** [sschmid/Entitas-CSharp#783] opened 2018-09-05 09:48 UTC
component name : StringData

in the MonoBehaviour script  update function :  

void Update () {
        _systems.Execute();
        _systems.Cleanup();

        count++;

        entity.ReplaceStringData(count.ToString()+"a");    //replace more time  at one frame
        entity.ReplaceStringData(count.ToString()+"b"); 
        entity.ReplaceStringData(count.ToString()+"c");
        entity.ReplaceStringData(count.ToString()+"d");
        entity.ReplaceStringData(count.ToString()+"e");
        
    }

[](url)
in the  class StringDataSystem : ReactiveSystem<GameEntity> .     

  protected override void Execute(List<GameEntity> entities)
    {
        foreach (var item in entities)
        {
            UnityEngine.Debug.Log(" String: data " + item.stringData.Data);
        }
    }

unity Log : 

 String: data 1e
 String: data 2e
 String: data 3e
 String: data 4e
  .....

I can't get  the . Reactive   value  like     1a 1b 1c  1d 

just . get the last value  *e .

**Comment by StormRene** [comment] 2018-09-05 10:10
Hello and welcome to the community. Please note the correct formatting of your code. Your request is pretty hard to read.

The behavior shown is intentional. Reactive systems are triggered by changes and pass the current data from the component. The state after your processing for the next Execute is *e. As a result, you also get this data in the system.

**Comment by xiaomingfun** [comment] 2018-09-05 10:26
GameControllerTest.cs

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Entitas;
using UnityEditor;
public class GameControllerTest : MonoBehaviour
{
    Systems _systems;
    // Use this for initialization
    void Start()
    {
        var contexts = Contexts.sharedInstance;
        _systems = CreateSystems(contexts);
        _systems.Initialize();
    }

    // Update is called once per frame  
    int count = 0;
    void Update()
    {
        _systems.Execute();
        _systems.Cleanup();

        count++;

        entity.ReplaceStringData(count.ToString() + "a");
        entity.ReplaceStringData(count.ToString() + "b");
        entity.ReplaceStringData(count.ToString() + "c");
        entity.ReplaceStringData(count.ToString() + "d");
        entity.ReplaceStringData(count.ToString() + "e");

    }

    private void OnDestroy()
    {
        _systems.TearDown();
    }

    GameEntity entity;

    Systems CreateSystems(Contexts contexts)
    {
        var s = new Feature("Root System")
           .Add(new StringDataSystem(contexts));
        entity = contexts.game.CreateEntity();
        entity.AddStringData("123");
        return s;
    }
}

`

StringDataComponent.cs

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Entitas;
public class StringDataComponent : IComponent {
    public string Data;

}

`
StringDataSystem.cs
`
using System.Collections.Generic;
using Entitas;

public class StringDataSystem : ReactiveSystem<GameEntity>
{
    GameContext _context;
    public StringDataSystem(Contexts contexts) : base(contexts.game)
    {
        _context = contexts.game;
    }

    protected override void Execute(List<GameEntity> entities)
    {
        foreach (var item in entities)
        {
            UnityEngine.Debug.Log(" String: data " + item.stringData.Data);
        }
    }

    protected override bool Filter(GameEntity entity)
    {
        return entity.hasStringData;
    }

    protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context)
    {
        return context.CreateCollector(GameMatcher.StringData);
    }

}

`

unity Log :

String: data 1e
String: data 2e
String: data 3e
String: data 4e
String: data 5e
.....

I change the value 5 times at one frame   :  count+ (a to e) 
but  after Update function, 
Unity just Debug the last value  I passed

@StormRene

**Comment by StormRene** [comment] 2018-09-05 10:54
As mentioned before: Please take into account the correct formatting of your code. Your follow-up message is even harder to read than the first one. 
The behavior shown is intentional. The system processes the current data of the component when it calls the Execute, which is always *e in your case.

**Comment by xiaomingfun** [comment] 2018-09-05 11:09
I just want  to say。  If I change the value   of  a component   more then once  by   the function  replace*****()  at  MonoBehaviour  update  ,  how many times the Reactive systems will execute  at one frame?

**Comment by StormRene** [comment] 2018-09-05 12:38
Only the current data of the component of each entity when the execute is called is transferred in the reactive system. Therefore, in your case: 1.

**Comment by xiaomingfun** [comment] 2018-09-05 23:46
I know you meaning. If I change the value more then once time at the same frame ,the  reactive system will just call execute only once with value current data . But I want  reactive system call execute each time I changed the value in one frame. What I can do for this ?

**Comment by StormRene** [comment] 2018-09-06 08:58
This behavior is not possible if the Execute is called only once between the individual changes to the data. Either you call Execute after each change or you use GroupEvents. With GroupEvents you can react directly to any change regardless of the Execute order. Here is the code:
```
gameContext.GetGroup(GameMatcher.StringData).OnEntityAdded += (group, entity, index, component) => Debug.Log("String: data " + entity.stringData.Data);
```
This method is called immediately when the component is added.

**Comment by xiaomingfun** [comment] 2018-09-07 05:15
the last code can work will

**Comment by sschmid** [comment] 2018-09-16 10:41
Summary:
The nature of reactive systems is to aggregate changes until you call `Execute()` the next time. When calling `Execute()` it will process all changed entities with their current set of components and corresponding values once. That's intended behaviour.

In order to react to any change immediately (and therefore outside of your defined system loop) is to use group observers as @StormRene mentioned.
This is not recommended for normal use, because it triggers code immediately and doesn't follow your system loop. In my experience there is just a very small set of use-cases, where you should favour group observers over reactive system.

**Closed by sschmid** 2018-09-16 10:41 UTC
