### ISSUE TITLE
Bug: Imposible set "Fast and Safe

### ISSUE THREAD

**Issue by AlexeyJKoshkin** [sschmid/Entitas-CSharp#387] opened 2017-04-19 18:17 UTC
![image](https://cloud.githubusercontent.com/assets/3306190/25195152/61e95976-2545-11e7-82af-6c638685d0fb.png)

**Comment by IsaiahKelly** [comment] 2017-04-20 02:37
Duplicate of issue #385. This is also a Unity related bug ([Issue ID 898295](https://issuetracker.unity3d.com/issues/playersettings-dot-setscriptingdefinesymbolsforgroup-doesnt-like-buildtargetgroup-dot-switch))

**Comment by sschmid** [comment] 2017-04-20 07:39
Will close. Duplicate, please refer to #385

**Closed by sschmid** 2017-04-20 07:39 UTC
Labels: duplicate
