### ISSUE TITLE
Entitas 0.47.7 Jenny failed to setup and gen code

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#561] opened 2018-01-17 06:13 UTC
Directly run jenny fix and jenny auto-import
![image](https://user-images.githubusercontent.com/7009368/35028321-78c89310-fb90-11e7-819b-8fbf1100cffe.png)

**Comment by optimisez** [comment] 2018-01-17 06:24
![image](https://user-images.githubusercontent.com/7009368/35028647-0b07beee-fb92-11e7-8671-ef719de3423c.png)

**Comment by optimisez** [comment] 2018-01-17 06:39
Renamed Entitas properties manually. Jenny doctor no problem but nothing happen when jenny gen. It's the same result when opening jenny server and client gen.

![image](https://user-images.githubusercontent.com/7009368/35028924-6233fcd6-fb93-11e7-8d68-13a2eca1a2c0.png)
![image](https://user-images.githubusercontent.com/7009368/35028978-a740695e-fb93-11e7-8b76-122bbfc099b7.png)

![image](https://user-images.githubusercontent.com/7009368/35029040-f0340d28-fb93-11e7-9a74-47e91eaccd03.png)

![image](https://user-images.githubusercontent.com/7009368/35029109-409036de-fb94-11e7-86db-7c5849631cb0.png)
![image](https://user-images.githubusercontent.com/7009368/35028915-4d0f9be4-fb93-11e7-967b-397e09bdda66.png)

**Comment by chiuan** [comment] 2018-01-17 07:51
how about new the properties file.

**Comment by optimisez** [comment] 2018-01-17 08:11
Ok. Problem fixed. The issue is due to the ```CodeGenerator``` folder name changed to ```Jenny```. 

Change this
```
Jenny.SearchPaths = CodeGenerator/Plugins, \
                            CodeGenerator/Plugins\Entitas, \
                            CodeGenerator/Plugins\Entitas.Roslyn, \
                            CodeGenerator\Plugins\Entitas, \
                            CodeGenerator\Plugins\Entitas.Roslyn, \
                            Assets\Entitas\Editor, \
                            CodeGenerator\Plugins\Jenny
```
To this
```
Jenny.SearchPaths = Jenny/Plugins, \
                            Jenny/Plugins\Entitas, \
                            Jenny/Plugins\Entitas.Roslyn, \ 
  ```

**Comment by Lazersquid** [comment] 2018-01-17 10:45
Yes same for me, everything works up to the point where I run `Jenny auto-import -s`.
I also get `The given assembly name or codebase was invalid (Exception from HRESULT: 0x80131047)`
And it's not adding any Plugins/PreProcessors/DataProviders/etc...

Project structure:
* Project/Assets/Entitas
* Project/Jenny
* Project/Jenny auto-import.bat
* Project/Preferences.properties

I took extra care to follow simons instruction on gitter:

> My setup is usually the following
> - Create a new Unity project
> - Copy Entitas into Assets folder
> - Assets -> Open C# project
> - Open Entitas Preferences
> - Click Auto-Import and  hit generate

> If everything is fine I extract the Jenny.zip into the root of the project and run
> ```
> $ Jenny/Jenny.exe fix
> $ Jenny/Jenny.exe auto-import -s
> ```

I tried adding additional search paths:
```
Jenny.SearchPaths = Assets/Entitas/Editor/Plugins/DesperateDevs, \
                    Assets/Entitas/Editor/Plugins/Entitas, \
                    Jenny, \
                    Jenny/Plugins, \
                    Jenny/Plugins\Entitas, \
                    Jenny/Plugins\Entitas.Roslyn, \
                    C:/Program Files/Unity/Editor/Data/Managed, \
                    C:/Program Files/Unity/Editor/Data/Managed/UnityEngine, \
                    C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity
```
I also tried `Jenny new Preferences.properties` and then `Jenny auto-import` but that results in the same error

**Comment by optimisez** [comment] 2018-01-17 11:57
Here's the Entitas.properties file for reference to people who failed to setup Jenny code gen properly.
[Entitas.properties.txt](https://github.com/sschmid/Entitas-CSharp/files/1638813/Entitas.properties.txt)

**Comment by sschmid** [comment] 2018-01-17 12:28
Just checked, you're right, there are issues on Windows.

Here's my default Preferens properties file with Roslyn set up already (remove .txt)

[Preferences.properties.txt](https://github.com/sschmid/Entitas-CSharp/files/1638907/Preferences.properties.txt)

**Comment by sschmid** [comment] 2018-01-17 12:31
Not sure what windows is complaining about yet again, if it's the latest roslyn libs, or the zip not being unblocked by the user first, or....  I have to investigate

**Comment by sschmid** [comment] 2018-01-17 13:31
@optimisez Ok, I can reproduce on Windows, works on Mac. `The given assembly name or codebase was invalid`. There seems to be (at least) 1 dll that he cannot load, although the file exists. Will investigate further

**Comment by sschmid** [comment] 2018-01-17 13:55
Ok, fixed on windows!

**Comment by sschmid** [comment] 2018-01-17 14:15
You can already use the fix by downloading the dlls listed here

https://github.com/sschmid/Entitas-CSharp/commit/dd90ab7224faee90fab563dbf6675adfdd0d85e0

are copy them into the Jenny folder

**Comment by sschmid** [comment] 2018-01-17 14:40
Fixed in [Entitas 0.47.8](https://github.com/sschmid/Entitas-CSharp/releases)

**Closed by sschmid** 2018-01-17 14:40 UTC
Labels: bug, code generator, windows

**Comment by optimisez** [comment] 2018-01-17 15:29
After putting the ```dd90ab7``` dlls. I get this error when gen code.
![image](https://user-images.githubusercontent.com/7009368/35050569-19adfdd6-fbde-11e7-9f6b-44dc9699ba7e.png)

![image](https://user-images.githubusercontent.com/7009368/35050634-3e726df0-fbde-11e7-99d7-8af280969966.png)

**Comment by sschmid** [comment] 2018-01-17 21:46
Seems like a dll got accidentally not built correctly. One DesperateDev dll seemed to be corrupt for that build only... New clean builds didn't have this issue... good to know
