### ISSUE TITLE
[Entitas 1.4] Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by roygear** [sschmid/Entitas-CSharp#628] opened 2018-02-27 04:06 UTC
Tested in Entitas 1.4,  a Unity new project, Window 7, Unity 2017.3.

Below error appear after execute Jenny auto-import 
```
Collection was modified; enumeration operation may not execute.
```

It is working fine for me using Entitas 1.2.

**Comment by optimisez** [comment] 2018-02-27 05:50
@sschmid Seems like 1.4 has bug on auto-import. Even empty fresh properties file auto-import does not work properly.

Empty fresh properties file auto-import
![image](https://user-images.githubusercontent.com/7009368/36712658-c44a8a24-1bc4-11e8-9423-35ac83f5e3c6.png)

Previous version properties file auto-import
![image](https://user-images.githubusercontent.com/7009368/36712722-03e14e02-1bc5-11e8-8f79-ac738d7ed7e5.png)

**Comment by nbreum15** [comment] 2018-02-27 12:04
As written on Gitter, a quick work-around is to download and run it through mono with `mono .\Jenny\Jenny.exe auto-import`. (Remember to set mono directory in system variables)

@sschmid When running unit-tests do you run it on Windows and Mac to make sure Jenny is compatible on both platforms?

**Comment by Randhall** [comment] 2018-02-27 13:25
Doesn't work even when run with mono.
I'm running windows 8 with unity 2017.3 freshly imported preferences without any change and it still fails to auto import.
When running the doctor it lists a bunch of unused keys in the preferences and running fix fails as well.
![capture](https://user-images.githubusercontent.com/3532917/36731114-99a501c6-1bc1-11e8-8401-3557dfe5da51.PNG)

**Comment by echeg** [comment] 2018-02-27 14:45
Same problem 

![](https://files.gitter.im/sschmid/Entitas-CSharp/Vbta/image.png)

**Comment by sschmid** [comment] 2018-02-27 17:19
Yes, can reproduce on windows. Will investigate

**Comment by sschmid** [comment] 2018-02-27 18:02
Jenny hasn't changed and is the same as 1.2 and 1.3, so it's kind of weird.
Loading assemblies behaves differently on windows, it was a threading issue.
Added a fix

**Comment by sschmid** [comment] 2018-02-27 18:03
You can override the dll in the Jenny folder to apply the patch.
[DesperateDevs.Utils.dll.zip](https://github.com/sschmid/Entitas-CSharp/files/1764124/DesperateDevs.Utils.dll.zip)

Will be in next release

**Comment by Randhall** [comment] 2018-02-27 18:11
Yup that did it for me thanks ;)
Now i can enjoy those delicious garbage free group iterations :D

**Comment by optimisez** [comment] 2018-02-27 20:08
@sschmid `Collection was modified; enumeration operation may not execute.` has been fixed but
I still have this issue. I notice that this error will pop up when I change DesperateDevs.CodeGeneration.Plugins.ProjectPath to Sources.csproj. Sources is the project that I create using Assembly Definition files that contain all the Entitas source code.
![image](https://user-images.githubusercontent.com/7009368/36751883-72cf289e-1c3c-11e8-8444-acb7632ccd93.png)

**Comment by sschmid** [comment] 2018-02-27 21:14
@optimisez can you do `-v` so I can see what the problem is? Did it work before?

**Comment by sschmid** [comment] 2018-02-27 21:34
@optimisez you requested a properties file, here it is :)

[Preferences.properties.zip](https://github.com/sschmid/Entitas-CSharp/files/1764779/Preferences.properties.zip)

**Comment by optimisez** [comment] 2018-02-27 21:52
@sschmid Ya. Previously version is working. 
```
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.CSharp.dll
  ? Loading Dependency: Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.dll
Opened Sources
Parsing Sources
Complete Sources
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DesperateDevs.Utils.StringExtension.LowercaseFirst(String str)
   at Entitas.CodeGeneration.Plugins.CodeGeneratorExtentions.Replace(String template, String contextName)
   at Entitas.CodeGeneration.Plugins.CodeGeneratorExtentions.Replace(String template, ComponentData data, String contextName)
   at Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.generateInterface(ComponentData data)
   at Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.generate(ComponentData data)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.generate(String messagePrefix, IPreProcessor[] preProcessors, IDataProvider[] dataProviders, ICodeGenerator[] codeGenerators, IPostProcessor[] postProcessors)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.DryRun()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.DoctorCommand.run()
   at DesperateDevs.Serialization.CLI.Utils.AbstractPreferencesCommand.Run(String[] args)
   at DesperateDevs.CLI.Utils.CLIProgram.runCommand(String[] args)
```

**Comment by sschmid** [comment] 2018-02-27 22:13
Ok, fixed. Will be in next release

**Closed by sschmid** 2018-02-27 22:13 UTC

**Comment by sschmid** [comment] 2018-02-27 22:15
If you already want to patch the dll, here it is

[DesperateDevs.Utils.dll.zip](https://github.com/sschmid/Entitas-CSharp/files/1764891/DesperateDevs.Utils.dll.zip)
