### ISSUE TITLE
Using "client doctor" or "client gen" sometimes crashes server unhandled System.ObjectDisposedException

### ISSUE THREAD

**Issue by Draugor** [sschmid/Entitas-CSharp#529] opened 2017-12-22 11:07 UTC
Hi,

I'm using the new Entitas 46.3 from the asset store and the jenny.exe server crashes after using "client doctor" or "client gen" 1-3 times.

I'm working on windows, used a new unity project with a fresh import from the asset store.

![](https://i.imgur.com/SAbmJgY.png)

Cheers

**Comment by sschmid** [comment] 2017-12-22 15:56
Hi, thanks for posting! I will try to reproduce after the holidays.

**Comment by roygear** [comment] 2017-12-23 13:50
this may be a bug of Unity 2017.2.
2017.3 seems fixed.

**Comment by sschmid** [comment] 2017-12-25 22:26
Ok cool. I will probably add a safety check to avoid this error. I really wanted to avoid any safety checks because I'm still convinced that this cannot happen :) but as it turns out, I'm wrong and it seems to behave differently on Windows, so I will surrender, give up, and add a safety check :)

**Comment by Draugor** [comment] 2017-12-28 19:16
i just installed unity 2017.3.0f3 and tried it, and it still happens. 
it happens even without having unity open (after a few tries).
the error message suggests it has something to do with the server <-> client socket connection so unity version shouldn't affect that.

**Comment by sschmid** [comment] 2018-01-10 23:39
Hi, fixed in [Entitas 0.47.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.47.0)

**Closed by sschmid** 2018-01-10 23:39 UTC
